routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestController;
// use App\Http\Controllers\Blog\IndexController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\Category\CategoryController;
use App\Http\Controllers\Admin\Tag\TagController;
use App\Http\Controllers\Admin\Post\PostController;
use App\Http\Controllers\Admin\Vocal\VocalController;
use App\Http\Controllers\Admin\Song\SongController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\Tutorial\TutorialController;
use App\Http\Controllers\Admin\Role\RoleController;
use App\Http\Controllers\Admin\OriginalSong\OriginalSongController;
use App\Http\Controllers\Front\MailController;
use App\Http\Controllers\Front\SongBaseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.pages.index');
    // return view('welcome');
})->name('mainPage');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::namespace('App\Http\Controllers\Blog')->group(function() {
    Route::get('/blog', 'IndexController');
});

Route::middleware(['adminWriter'])->prefix('admin')->group(function() {
    Route::get('/', [MainController::class, 'index'])->name('adminIndex');
    Route::resource('vocal', VocalController::class);
    Route::resource('song', SongController::class);
    Route::resource('originalsong', OriginalSongController::class);
    Route::resource('tutorial', TutorialController::class);
});

Route::middleware(['admin'])->prefix('admin')->group(function() {
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
    Route::post('/setWriter/{user}', [RoleController::class, 'setWriter'])->name('setWriter');
    Route::post('/unsetWriter/{user}', [RoleController::class, 'unsetWriter'])->name('unsetWriter');

    Route::get('pending/song', [SongController::class, 'pending'])->name('song.pending');
    Route::put('song/{song}/approve', [SongController::class, 'approval'])->name('song.approve');
});

Route::post('/sendMail', [MailController::class, 'sendMail'])->name('feedback');

Route::get('/songs', [SongBaseController::class, 'index'])->name('allSongs');
Route::get('/song/{song}', [SongBaseController::class, 'show'])->name('showSong');

// тестовые роуты не нужны совсем
Route::get('/getTest', [TestController::class, 'getTest']);
Route::get('/getSong', [TestController::class, 'getSong']);
Route::get('/getPostsTags', [TestController::class, 'getPostsTags']);
Route::get('/getTagsPosts', [TestController::class, 'getTagsPosts']);
// тестовые роуты не нужны совсем

app/Models/Vocal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use App\Http\Requests\VocalRequest;
use Illuminate\Support\Facades\Storage;

class Vocal extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'title',
        'vocal',
        'song_id',
    ];

    public function song()
    {
        return $this->belongsTo(Song::class);
    }

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public static function uploadAudio(VocalRequest $request, $vocal = null)
    {
        if ($request->hasFile('vocal')) {
            if ($vocal) {
                Storage::delete($vocal);
            }
            $folder = date('Y-m-d');
            return $request->file('vocal')->store("vocal/{$folder}");
        }
        return $vocal ? $vocal : null;
    }

    public function getAudio()
    {
        if (! $this->vocal) {
            return null;
        }
        return asset("uploads/{$this->vocal}");
    }
}

app/Http/Controllers/Admin/Vocal/VocalController.php
<?php

namespace App\Http\Controllers\Admin\Vocal;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\VocalRequest;
use App\Models\Vocal;
use App\Models\Song;
use Illuminate\Support\Facades\Storage;

class VocalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vocals = Vocal::orderBy('created_at', 'DESC')->get();
        return view('admin.vocal.index', compact('vocals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $songs = Song::pluck('title', 'id')->all();
        return view('admin.vocal.create', compact('songs',));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VocalRequest $request)
    {
        $data = $request->validated();
        
        $data['vocal'] = Vocal::uploadAudio($request);
        $vocal = Vocal::create($data);
        return redirect()->route('vocal.index')->with('success', 'Партия добавлена!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $vocal = Vocal::where('slug', $slug)->first();
        if (! $vocal) {
            return back()->with('error', 'Партия не найдена!');
        }
        $songs = Song::pluck('title', 'id')->all();
        return view('admin.vocal.edit', compact('vocal', 'songs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VocalRequest $request, $slug)
    {
        $vocal = Vocal::where('slug', $slug)->first();
        if (! $vocal) {
            return back()->with('error', 'Партия не найдена!');
        }

        $data = $request->validated();

        $data['vocal'] = Vocal::uploadAudio($request, $vocal->vocal);
        $vocal->update($data);
        return redirect()
            ->route('vocal.index')->with('success', 'Партия изменена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $vocal = Vocal::where('slug', $slug)->first();

        if ($vocal) {
            if ($vocal->vocal) {
                Storage::delete($vocal->vocal);
            }
            $vocal->delete();
            return redirect()->route('vocal.index')->with('success', 'Партия удалена!');
        }
        return back()->with('error', 'Партия не найдена!');
    }
}

resources/views/admin/vocal/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60"
            width="60">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('admin.includes.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Новая вокальная партия</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <a class="btn btn-primary float-right" href="{{ route('vocal.index') }}" role="button">Список
                            партий</a>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <form method="post" action="{{ route('vocal.store')}}" enctype="multipart/form-data">
                            @csrf
                            <p>Добавляйте партии очень внимательно т.к. редактировать их сложнее. Сложность в том что
                                при
                                редактировании, файл который был прикреплен при создании, будет
                                отсутствовать в форме правки, как будто его нет ,
                                хотя под полем ввода файла, будет видно, что файл есть. Но на самом деле его нужно
                                добавить в любом случае повторно. Это из за безопасности, и ничего пока с этим поделать
                                нельзя. Иногда даже проще просто удалить партию вокала и создать новую чем изменить
                                существующую
                            </p>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="vocalCreate">Название партии</label>
                                    <input type="text" name="title"
                                        class="form-control @error('title') is-invalid @enderror" id="vocalCreate"
                                        placeholder="Введите название статьи" value="{{ old('title') }}">
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Песня</label>
                                    <select class="form-control" id="song_id" name="song_id">
                                        @foreach($songs as $id => $title)
                                        <option value="{{$id}}" @if (old('song_id')==$id) selected @endif>
                                            {{$title}}
                                        </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Аудио партия</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" name="vocal" class="custom-file-input"
                                                id="exampleInputFile">
                                            <label class="custom-file-label" for="exampleInputFile">Выберите
                                                файл</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>SongBase</strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.1.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
@endsection
@section('scriptBottom')
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<script>
    $(function () {
        bsCustomFileInput.init();
    });

</script>
@endsection

resources/views/admin/vocal/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60"
            width="60">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('admin.includes.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Изменить вокальную партию</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <a class="btn btn-primary float-right" href="{{ route('vocal.index') }}" role="button">Список
                            партий</a>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <form method="post" action="{{ route('vocal.update', $vocal)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <p>Добавляйте партии очень внимательно т.к. редактировать их сложнее. Сложность в том что при
                                редактировании, файл который был прикреплен при создании, будет
                                отсутствовать в форме правки, как будто его нет ,
                                хотя под полем ввода файла, будет видно, что файл есть. Но на самом деле его нужно
                                добавить в любом случае повторно. Это из за безопасности, и ничего пока с этим поделать
                                нельзя. Иногда даже проще просто удалить партию вокала и создать новую чем изменить существующую
                            </p>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="vocalCreate">Название партии</label>
                                    <input type="text" name="title"
                                        class="form-control @error('title') is-invalid @enderror" id="vocalCreate"
                                        placeholder="Введите название статьи" value="{{ $vocal->title }}">
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Песня</label>
                                    <select class="form-control" id="song_id" name="song_id">
                                        @foreach($songs as $id => $title)
                                        <option @if ($id===$vocal->song_id) selected @endif
                                            value="{{$id}}">{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Аудио партия</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" name="vocal" class="custom-file-input"
                                                id="exampleInputFile" value='{{$vocal->getAudio()}}'>
                                            <label class="custom-file-label" for="exampleInputFile">Выберите
                                                файл</label>
                                        </div>
                                    </div>
                                </div>
                                @if ($vocal->getAudio())
                                <audio controls="controls" src="{{$vocal->getAudio()}}"></audio>
                                @else
                                <p>no audio</p>
                                @endif
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>SongBase</strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.1.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
@endsection
@section('scriptBottom')
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<script>
    $(function () {
        bsCustomFileInput.init();
    });

</script>
@endsection

resources/views/admin/vocal/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60"
            width="60">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('admin.includes.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Партии вокала</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <a class="btn btn-primary float-right" href="{{ route('vocal.create') }}" role="button">Добавить
                            партию</a>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Все партии вокала</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="vocal-table" class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>№</th>
                                            <th>Название партии</th>
                                            <th>Принадлежит песне</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($vocals as $key => $vocal)
                                        <tr>
                                            <td>{{$key + 1}}</td>
                                            <td>{{$vocal->title}}</td>
                                            <td>{{$vocal->song->title}}</td>
                                            <td>
                                                <a href="{{ route('vocal.edit', $vocal) }}"
                                                    class="btn btn-info btn-sm float-left mr-1">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                @role('admin')
                                                <form action="{{ route('vocal.destroy', $vocal) }}" method="post"
                                                    class="float-left">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"
                                                        onclick="return confirm('Подтвердите удаление')">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                                @endrole

                                            </td>
                                        </tr>
                                        @empty
                                        <p>No vocals</p>
                                        @endforelse

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>№</th>
                                            <th>Название партии</th>
                                            <th>Принадлежит песне</th>
                                            <th>Actions</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>SongBase</strong>
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.1.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
@endsection