routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestController;
// use App\Http\Controllers\Blog\IndexController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\Category\CategoryController;
use App\Http\Controllers\Admin\Tag\TagController;
use App\Http\Controllers\Admin\Post\PostController;
use App\Http\Controllers\Admin\Vocal\VocalController;
use App\Http\Controllers\Admin\Song\SongController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\Tutorial\TutorialController;
use App\Http\Controllers\Admin\Role\RoleController;
use App\Http\Controllers\Admin\OriginalSong\OriginalSongController;
use App\Http\Controllers\Front\MailController;
use App\Http\Controllers\Front\SongBaseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.pages.index');
    // return view('welcome');
})->name('mainPage');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::namespace('App\Http\Controllers\Blog')->group(function() {
    Route::get('/blog', 'IndexController');
});

Route::middleware(['adminWriter'])->prefix('admin')->group(function() {
    Route::get('/', [MainController::class, 'index'])->name('adminIndex');
    Route::resource('vocal', VocalController::class);
    Route::resource('song', SongController::class);
    Route::resource('originalsong', OriginalSongController::class);
    Route::resource('tutorial', TutorialController::class);
});

Route::middleware(['admin'])->prefix('admin')->group(function() {
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
    Route::post('/setWriter/{user}', [RoleController::class, 'setWriter'])->name('setWriter');
    Route::post('/unsetWriter/{user}', [RoleController::class, 'unsetWriter'])->name('unsetWriter');

    Route::get('pending/song', [SongController::class, 'pending'])->name('song.pending');
    Route::put('song/{song}/approve', [SongController::class, 'approval'])->name('song.approve');
});

Route::post('/sendMail', [MailController::class, 'sendMail'])->name('feedback');

Route::get('/songs', [SongBaseController::class, 'index'])->name('allSongs');
Route::get('/song/{song}', [SongBaseController::class, 'show'])->name('showSong');

// тестовые роуты не нужны совсем
Route::get('/getTest', [TestController::class, 'getTest']);
Route::get('/getSong', [TestController::class, 'getSong']);
Route::get('/getPostsTags', [TestController::class, 'getPostsTags']);
Route::get('/getTagsPosts', [TestController::class, 'getTagsPosts']);
// тестовые роуты не нужны совсем

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'title',
        'content',
        'category_id',
        'thumbnail',
        'audio',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public static function uploadImage(Request $request, $image = null)
    {
        if ($request->hasFile('thumbnail')) {
            if ($image) {
                Storage::delete($image);
            }
            $folder = date('Y-m-d');
            return $request->file('thumbnail')->store("images/{$folder}");
        }
        return $image ? $image : null;
    }

    public static function uploadAudio(Request $request, $audio = null)
    {
        if ($request->hasFile('audio')) {
            if ($audio) {
                Storage::delete($audio);
            }
            $folder = date('Y-m-d');
            return $request->file('audio')->store("audio/{$folder}");
        }
        return $audio ? $audio : null;
    }

    public function getImage()
    {
        if (! $this->thumbnail) {
            return asset('no-image.jpg');
        }
        return asset("uploads/{$this->thumbnail}");
    }

    public function getAudio()
    {
        if (! $this->audio) {
            return null;
        }
        return asset("uploads/{$this->audio}");
    }
}

app/Http/Controllers/Admin/Post/PostController.php
<?php

namespace App\Http\Controllers\Admin\Post;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('created_at', 'DESC')->get();
        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('title', 'id')->all();
        $tags = Tag::pluck('title', 'id')->all();
        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $data = $request->validated();
        
        $data['audio'] = Post::uploadAudio($request);
        $data['thumbnail'] = Post::uploadImage($request);
        $post = Post::create($data);
        $post->tags()->sync($request->tags);
        return redirect()->route('post.index')->with('success', 'Статья добавлена!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $post = Post::where('slug', $slug)->first();
        if (! $post) {
            return back()->with('error', 'Статья не найдена!');
        }
        $categories = Category::pluck('title', 'id')->all();
        $tags = Tag::pluck('title', 'id')->all();
        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $slug)
    {
        $post = Post::where('slug', $slug)->first();
        if (! $post) {
            return back()->with('error', 'Статья не найдена!');
        }

        $data = $request->validated();

        $data['audio'] = Post::uploadAudio($request, $post->audio);
        $data['thumbnail'] = Post::uploadImage($request, $post->thumbnail);

        $post->update($data);
        $post->tags()->sync($request->tags);
        return redirect()
            ->route('post.index')->with('success', 'Статья изменена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $post = Post::where('slug', $slug)->first();

        if ($post) {
            if ($post->thumbnail) {
                Storage::delete($post->thumbnail);
            }
            if ($post->audio) {
                Storage::delete($post->audio);
            }
            $post->delete();
            return redirect()->route('post.index')->with('success', 'Статья удалена!');
        }
        return back()->with('error', 'Статья не найдена!');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Новая статья</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <a class="btn btn-primary float-right" href="{{ route('post.index') }}" role="button">Список статей</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <form method="post" action="{{ route('post.store')}}" enctype="multipart/form-data">
              @csrf
              <div class="card-body">
                  <div class="form-group">
                      <label for="postCreate">Название статьи</label>
                      <input type="text" name="title"
                            class="form-control @error('title') is-invalid @enderror"
                            id="postCreate"
                            placeholder="Введите название статьи"
                            value="{{ old('title') }}">
                  </div>
                  <div class="form-group">
                      <label for="exampleInputCat3">Контент</label>
                      <textarea name="content" rows="5"
                          class="form-control @error('content') is-invalid @enderror" id="exampleInputCat3"
                          placeholder="Введите описание Статьи"></textarea>
                  </div>
                  {{-- {{print_r($categories)}} --}}
                  <div class="form-group">
                      <label for="category_id">Категория</label>
                      <select class="form-control" id="category_id" name="category_id">
                          @foreach($categories as $id => $title)
                              <option value="{{$id}}">{{$title}}</option>
                          @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="tags">Тэги</label>
                      <select class="select2" id="tags" name="tags[]" multiple="multiple"
                          data-placeholder="Выбрать тэги" style="width: 100%;">
                          @foreach($tags as $id => $title)
                              <option value="{{$id}}">{{$title}}</option>
                          @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="exampleInputFile">Картинка</label>
                      <div class="input-group">
                          <div class="custom-file">
                              <input type="file" name="thumbnail" class="custom-file-input" id="exampleInputFile">
                              <label class="custom-file-label" for="exampleInputFile">Выберите файл</label>
                          </div>
                      </div>
                  </div>
                  <div class="form-group">
                      <label for="exampleInputFile">Аудио</label>
                      <div class="input-group">
                          <div class="custom-file">
                              <input type="file" name="audio" class="custom-file-input" id="exampleInputFile">
                              <label class="custom-file-label" for="exampleInputFile">Выберите файл</label>
                          </div>
                      </div>
                  </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Отправить</button>
              </div>
          </form>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Изменить статью</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <a class="btn btn-primary float-right" href="{{ route('post.index') }}" role="button">Список статей</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <form method="post" action="{{ route('post.update', $post)}}" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="card-body">
                  <div class="form-group">
                      <label for="postCreate">Название статьи</label>
                      <input type="text" name="title"
                            class="form-control @error('title') is-invalid @enderror"
                            id="postCreate"
                            placeholder="Введите название статьи"
                            value="{{ $post->title }}">
                  </div>
                  <div class="form-group">
                      <label for="exampleInputCat3">Контент</label>
                      <textarea name="content" rows="5"
                          class="form-control @error('content') is-invalid @enderror" id="exampleInputCat3"
                          placeholder="Введите описание Статьи">{{ $post->content }}</textarea>
                  </div>
                  <div class="form-group">
                      <label for="category_id">Категория</label>
                      <select class="form-control" id="category_id" name="category_id">
                        @foreach($categories as $id => $title)
                            <option @if ($id === $post->category_id) selected @endif
                            value="{{$id}}">{{$title}}</option>
                        @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="tags">Тэги</label>
                      <select class="select2" id="tags" name="tags[]" multiple="multiple"
                          data-placeholder="Выбрать тэги" style="width: 100%;">
                          @foreach($tags as $id => $title)
                              <option @if (in_array($id, $post->tags->pluck('id')->all())) selected @endif
                              value="{{$id}}">{{$title}}</option>
                          @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="exampleInputFile">Картинка</label>
                      <div class="input-group">
                          <div class="custom-file">
                              <input type="file" name="thumbnail" class="custom-file-input" id="exampleInputFile">
                              <label class="custom-file-label" for="exampleInputFile">Выберите файл</label>
                          </div>
                      </div>
                  </div>
                  <img src="{{ $post->getImage() }}" alt="" width="200" class="mt-2 img-thumbnail">
                  <div class="form-group">
                      <label for="exampleInputFile">Аудио</label>
                      <div class="input-group">
                          <div class="custom-file">
                              <input type="file" name="audio" class="custom-file-input" id="exampleInputFile">
                              <label class="custom-file-label" for="exampleInputFile">Выберите файл</label>
                          </div>
                      </div>
                  </div>
                  @if ($post->getAudio())
                    <audio controls="controls" src="{{$post->getAudio()}}" ></audio>
                  @else
                    <p>no audio</p>
                  @endif
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Отправить</button>
              </div>
          </form>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Статьи</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          <a class="btn btn-primary float-right" href="{{ route('post.create') }}" role="button">Добавить статью</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <div class="card">
              <div class="card-header">
                <h3 class="card-title">Все статьи</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="post-table" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>№</th>
                    <th>Название статьи</th>
                    <th>Контент</th>
                    <th>Картинка</th>
                    <th>Медиа</th>
                    <th>Категория</th>
                    <th>Тэги</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  @forelse ($posts as $key => $post)
                    <tr>
                      <td>{{$key + 1}}</td>
                      <td>{{$post->title}}</td>
                      <td>{{Str::limit($post->content, 20)}}</td>
                      <td><img src="{{$post->getImage()}}" alt="" style = "width:100px"></td>
                      <td>
                        @if ($post->getAudio())
                          <audio controls="controls" src="{{$post->getAudio()}}" ></audio>
                        @else
                          no audio
                        @endif
                      </td>
                      <td>{{$post->category->title}}</td>
                      <td>{{$post->tags->pluck('title')->join(', ')}}</td>
                      <td>
                          <a href="{{ route('post.edit', $post) }}" class="btn btn-info btn-sm float-left mr-1">
                              <i class="fas fa-pencil-alt"></i>
                          </a>

                          <form action="{{ route('post.destroy', $post) }}" method="post" class="float-left">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger btn-sm"
                                      onclick="return confirm('Подтвердите удаление')">
                                  <i class="fas fa-trash-alt"></i>
                              </button>
                          </form>
                      </td>
                    </tr>
                  @empty
                      <p>No posts</p>
                  @endforelse

                  </tbody>
                  <tfoot>
                  <tr>
                    <th>№</th>
                    <th>Название статьи</th>
                    <th>Контент</th>
                    <th>Картинка</th>
                    <th>Медиа</th>
                    <th>Категория</th>
                    <th>Тэги</th>
                    <th>Actions</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection