routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestController;
// use App\Http\Controllers\Blog\IndexController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\Category\CategoryController;
use App\Http\Controllers\Admin\Tag\TagController;
use App\Http\Controllers\Admin\Post\PostController;
use App\Http\Controllers\Admin\Vocal\VocalController;
use App\Http\Controllers\Admin\Song\SongController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\Tutorial\TutorialController;
use App\Http\Controllers\Admin\Role\RoleController;
use App\Http\Controllers\Admin\OriginalSong\OriginalSongController;
use App\Http\Controllers\Front\MailController;
use App\Http\Controllers\Front\SongBaseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.pages.index');
    // return view('welcome');
})->name('mainPage');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::namespace('App\Http\Controllers\Blog')->group(function() {
    Route::get('/blog', 'IndexController');
});

Route::middleware(['adminWriter'])->prefix('admin')->group(function() {
    Route::get('/', [MainController::class, 'index'])->name('adminIndex');
    Route::resource('vocal', VocalController::class);
    Route::resource('song', SongController::class);
    Route::resource('originalsong', OriginalSongController::class);
    Route::resource('tutorial', TutorialController::class);
});

Route::middleware(['admin'])->prefix('admin')->group(function() {
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
    Route::post('/setWriter/{user}', [RoleController::class, 'setWriter'])->name('setWriter');
    Route::post('/unsetWriter/{user}', [RoleController::class, 'unsetWriter'])->name('unsetWriter');

    Route::get('pending/song', [SongController::class, 'pending'])->name('song.pending');
    Route::put('song/{song}/approve', [SongController::class, 'approval'])->name('song.approve');
});

Route::post('/sendMail', [MailController::class, 'sendMail'])->name('feedback');

Route::get('/songs', [SongBaseController::class, 'index'])->name('allSongs');
Route::get('/song/{song}', [SongBaseController::class, 'show'])->name('showSong');

// тестовые роуты не нужны совсем
Route::get('/getTest', [TestController::class, 'getTest']);
Route::get('/getSong', [TestController::class, 'getSong']);
Route::get('/getPostsTags', [TestController::class, 'getPostsTags']);
Route::get('/getTagsPosts', [TestController::class, 'getTagsPosts']);
// тестовые роуты не нужны совсем

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Tag extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'title',
    ];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
    
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/Tag/TagController.php
<?php

namespace App\Http\Controllers\Admin\Tag;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Tag;
use App\Http\Requests\TagRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderBy('created_at', 'DESC')->get();
        return view('admin.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\TagRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        Tag::create($request->validated());
        return redirect()->route('tag.index')->with('success', 'Тэг добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $tag = Tag::where('slug', $slug)->first();
        if (! $tag) {
            return back()->with('error', 'Тэг не найден!');
        }
        return view('admin.tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\TagRequest  $request
     * @param  \App\Models\Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $tag->update($request->validated());
        return redirect()
            ->route('tag.index')->with('success', 'Тэг изменен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $tag = Tag::where('slug', $slug)->first();
        if ($tag) {
            $tag->delete();
            return redirect()->route('tag.index')->with('success', 'Тэг удален!');
        }
        return back()->with('error', 'Тэг не найден!');
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Новый тэг</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <a class="btn btn-primary float-right" href="{{ route('tag.index') }}" role="button">Список тегов</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <form method="post" action="{{ route('tag.store')}}">
              @csrf
              <div class="card-body">
                  <div class="form-group">
                      <label for="tagCreate">Название тега</label>
                      <input type="text" name="title"
                            class="form-control @error('title') is-invalid @enderror"
                            id="tagCreate"
                            placeholder="Введите название тега"
                            value="{{ old('title') }}">
                  </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Отправить</button>
              </div>
          </form>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Изменить тэг</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <a class="btn btn-primary float-right" href="{{ route('tag.index') }}" role="button">Список тэгов</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <form method="post" action="{{ route('tag.update', $tag)}}">
              @csrf
              @method('PUT')
              <div class="card-body">
                  <div class="form-group">
                      <label for="tagCreate">Название тэга</label>
                      <input type="text" name="title"
                            class="form-control @error('title') is-invalid @enderror"
                            id="tagCreate"
                            placeholder="Введите название тэга"
                            value="{{$tag->title}}">
                  </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Отправить</button>
              </div>
          </form>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('') }}dist/img/songLogo.jpg" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('admin.includes.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Тэги</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
          <a class="btn btn-primary float-right" href="{{ route('tag.create') }}" role="button">Добавить тэг</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
          <div class="card">
              <div class="card-header">
                <h3 class="card-title">Все тэги</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tag-table" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>№</th>
                    <th>Название тэга</th>
                    <th>Количество постов</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  @forelse ($tags as $key => $tag)
                    <tr>
                      <td>{{$key + 1}}</td>
                      <td>{{$tag->title}}</td>
                      <td>{{$tag->posts->count()}}</td>
                      <td>
                          <a href="{{ route('tag.edit', $tag) }}" class="btn btn-info btn-sm float-left mr-1">
                              <i class="fas fa-pencil-alt"></i>
                          </a>

                          <form action="{{ route('tag.destroy', $tag) }}" method="post" class="float-left">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger btn-sm"
                                      onclick="return confirm('Подтвердите удаление')">
                                  <i class="fas fa-trash-alt"></i>
                              </button>
                          </form>
                      </td>
                    </tr>
                  @empty
                      <p>No tags</p>
                  @endforelse

                  </tbody>
                  <tfoot>
                  <tr>
                    <th>№</th>
                    <th>Название тэга</th>
                    <th>Количество постов</th>
                    <th>Actions</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>SongBase</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
@endsection