routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestController;
// use App\Http\Controllers\Blog\IndexController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\Category\CategoryController;
use App\Http\Controllers\Admin\Tag\TagController;
use App\Http\Controllers\Admin\Post\PostController;
use App\Http\Controllers\Admin\Vocal\VocalController;
use App\Http\Controllers\Admin\Song\SongController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\Tutorial\TutorialController;
use App\Http\Controllers\Admin\Role\RoleController;
use App\Http\Controllers\Admin\OriginalSong\OriginalSongController;
use App\Http\Controllers\Front\MailController;
use App\Http\Controllers\Front\SongBaseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.pages.index');
    // return view('welcome');
})->name('mainPage');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::namespace('App\Http\Controllers\Blog')->group(function() {
    Route::get('/blog', 'IndexController');
});

Route::middleware(['adminWriter'])->prefix('admin')->group(function() {
    Route::get('/', [MainController::class, 'index'])->name('adminIndex');
    Route::resource('vocal', VocalController::class);
    Route::resource('song', SongController::class);
    Route::resource('originalsong', OriginalSongController::class);
    Route::resource('tutorial', TutorialController::class);
});

Route::middleware(['admin'])->prefix('admin')->group(function() {
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    Route::resource('post', PostController::class);
    Route::resource('user', UserController::class);
    Route::post('/setWriter/{user}', [RoleController::class, 'setWriter'])->name('setWriter');
    Route::post('/unsetWriter/{user}', [RoleController::class, 'unsetWriter'])->name('unsetWriter');

    Route::get('pending/song', [SongController::class, 'pending'])->name('song.pending');
    Route::put('song/{song}/approve', [SongController::class, 'approval'])->name('song.approve');
});

Route::post('/sendMail', [MailController::class, 'sendMail'])->name('feedback');

Route::get('/songs', [SongBaseController::class, 'index'])->name('allSongs');
Route::get('/song/{song}', [SongBaseController::class, 'show'])->name('showSong');

// тестовые роуты не нужны совсем
Route::get('/getTest', [TestController::class, 'getTest']);
Route::get('/getSong', [TestController::class, 'getSong']);
Route::get('/getPostsTags', [TestController::class, 'getPostsTags']);
Route::get('/getTagsPosts', [TestController::class, 'getTagsPosts']);
// тестовые роуты не нужны совсем

resources/views/admin/includes/mainscripts.blade.php
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.j') }}s"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('dist/js/demo.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('dist/js/pages/dashboard.js') }}"></script>
<!-- select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- transpose -->
<script src="{{ asset('transpose/jquery.transposer.js') }}"></script>

resources/views/admin/includes/mainstyles.blade.php
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- select2 -->
  <link rel="stylesheet" href="{{ asset('/plugins/select2/css/select2.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">
  <!-- transpose -->
  <link rel="stylesheet" href="{{ asset('transpose/jquery.transposer.css') }}">

resources/views/admin/includes/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('mainPage') }}" class="brand-link">
        <img src="{{ asset('dist/img/songLogo.jpg') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Song Base</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('') }}dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{Auth::user()->name}}</a>
            </div>




        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                @role('admin')
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <!-- <i class="nav-icon fas fa-tachometer-alt"></i> -->
                        <i class="nav-icon far fa-list-alt"></i>
                        <p>
                            Категории
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $categoryCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('category.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список категорий</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('category.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить категорию</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <i class="nav-icon fas fa-tags"></i>
                        <p>
                            Тэги
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $tagCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('tag.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список тэгов</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('tag.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить тэг</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <i class="nav-icon fas fa-clipboard"></i>
                        <p>
                            Статьи
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $postCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('post.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список статей</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('post.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить статью</p>
                            </a>
                        </li>
                    </ul>
                </li>
                @endrole

                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <i class="nav-icon fas fa-microphone"></i>
                        <p>
                            Оригиналы песен
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $originalCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('originalsong.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список песен</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('originalsong.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить песню</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <i class="nav-icon fas fa-music"></i>
                        <p>
                            Партии вокала
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $vocalCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('vocal.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список партий</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('vocal.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить партию</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                    <i class="nav-icon fas fa-compact-disc"></i>
                        <p>
                            Песни
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $songCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('song.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список песен</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('song.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить песню</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                    <i class="nav-icon fas fa-book"></i>
                        <p>
                            Туториалы
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $tutorialCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('tutorial.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список туториалов</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('tutorial.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить туториал</p>
                            </a>
                        </li>
                    </ul>
                </li>
                @role('admin')
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                    <i class="nav-icon fas fa-user"></i>
                        <p>
                            Пользователи
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $userCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('user.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список пользователей</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('user.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Добавить пользователя</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item nav-opening">
                    <a href="#" class="nav-link nav-isactive">
                        <i class="nav-icon fas fa-check-circle"></i>
                        <p>
                            На одобрение
                            <i class="right fas fa-angle-left"></i>
                            <span class="badge badge-info right">{{ $pendingCount }}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{{ route('song.pending') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Список несен</p>
                            </a>
                        </li>
                    </ul>
                </li>
                @endrole
            </ul>
            <div class="fixed-bottom ml-2 mb-2" >
                <a class="btn btn-outline-danger" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                    Выйти из акккаунта
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>